# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-09 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScarletOnsell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 6, 2, 13, 928635), verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 6, 2, 13, 928659), verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('name', models.TextField(blank=True, null=True, verbose_name='\u540d\u79f0')),
                ('buy_num', models.IntegerField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u6570\u91cf')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='\u4ef7\u683c')),
                ('steam_price', models.FloatField(blank=True, null=True, verbose_name='steam \u4ef7\u683c')),
                ('sell_num', models.IntegerField(blank=True, null=True, verbose_name='\u5728\u552e\u6570\u91cf')),
                ('origin', models.TextField(blank=True, null=True, verbose_name='\u6570\u636e\u6765\u6e90')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'scarlet_onsell',
                'verbose_name_plural': '\u9970\u54c1\u5728\u552e',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 6, 2, 13, 927771), verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 6, 2, 13, 927804), verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('last_run', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='\u4e0a\u6b21\u8fd0\u884c\u65f6\u95f4')),
                ('next_run', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 6, 2, 13, 927857), verbose_name='\u4e0b\u6b21\u8fd0\u884c\u65f6\u95f4')),
                ('timeout', models.IntegerField(default=3600, verbose_name='\u53ef\u6267\u884c\u7684\u6700\u5927\u65f6\u95f4')),
                ('status', models.IntegerField(default=0, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('priority', models.IntegerField(default=1, verbose_name='\u4f18\u5148\u7ea7')),
                ('interval', models.IntegerField(default=0, verbose_name='\u8fd0\u884c\u95f4\u9694')),
                ('crawler', models.CharField(max_length=255, verbose_name='\u722c\u866b')),
                ('key', models.TextField(null=True, verbose_name='\u5173\u952e\u5b57')),
                ('data', models.TextField(null=True, verbose_name='\u4efb\u52a1\u6570\u636e')),
                ('producer_id', models.IntegerField(blank=True, null=True, verbose_name='\u751f\u4ea7\u8005id')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5206\u7c7b')),
                ('application', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e94\u7528')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'task',
                'verbose_name_plural': '\u722c\u866b\u4efb\u52a1',
            },
        ),
    ]
